import { defineCollection, z } from "astro:content";

const specSchema = z.object({
  label: z.string().min(1),
  value: z.string().min(1),
});

const projects = defineCollection({
  type: "data",
  schema: z.object({
    slug: z.string().min(1),
    sortOrder: z.number().int().nonnegative(),
    cardTitle: z.string().min(1),
    cardDescriptor: z.string().min(1),
    cardSystem: z.string().min(1),
    cardScatter: z.string().default(""),
    cardImage: z.string().nullable(),
    cardImageMobile: z.string().optional().nullable(),
    cardHolographic: z.boolean().default(false),
    cardLightText: z.boolean().default(true),
    panelTitle: z.string().min(1),
    panelDescription: z.string().min(1),
    panelSpecs: z.array(specSchema).min(1),
  }),
});

const stickers = defineCollection({
  type: "data",
  schema: z.object({
    sortOrder: z.number().int().nonnegative(),
    id: z.string().min(1),
    slug: z.string().min(1),
    ticker: z.string().min(1),
    title: z.string().min(1),
    tagline: z.string().min(1),
    ask: z.string().min(1),
    availableCount: z.union([z.number().int(), z.string()]),
    editionTotal: z.union([z.number().int(), z.string()]),
    status: z.enum([
      "LISTED",
      "BEYOND_TRANSACTION",
      "SOLD_OUT",
      "NEGOTIABLE",
      "SUBSCRIPTION",
      "RESERVED",
      "SOLD",
      "Pre-Incubation Phase 4",
    ]),
    provenance: z.string().min(1),
    contactEmail: z.string().email(),
    imageUrl: z.string().optional(),
    imageAlt: z.string().optional(),
    gallery: z.array(z.string()).default([]),
    description: z.string().optional(),
    downloadUrl: z.string().optional(),
    downloadLabel: z.string().optional(),
    playlistUrl: z.string().optional(),
    playlistLabel: z.string().optional(),
    dimensions: z.string().optional(),
    material: z.string().optional(),
    year: z.string().optional(),
    sentimentalValue: z.string().optional(),
    ambassadorMission: z.string().optional(),
    whyThisMatters: z.string().optional(),
    theoryCore: z.string().optional(),
    subscriptionModel: z.string().optional(),
    showTermsAsLink: z.boolean().default(false),
    rarity: z.string().optional(),
    cosmicLevel: z.string().optional(),
    tags: z.array(z.string()).default([]),
  }),
});

const qBagProduct = z.object({
  slug: z.literal("q-bag"),
  sortOrder: z.number().int().nonnegative(),
  title: z.string().min(1),
  heroImage: z.string().min(1),
  heroAlt: z.string().min(1),
  heroTitle: z.string().min(1),
  introTagline: z.string().min(1),
  introLead: z.string().min(1),
  artworkCardTitle: z.string().min(1),
  artworkCardDescription: z.string().min(1),
  artworkCardButtonLabel: z.string().min(1),
  conceptCards: z
    .array(
      z.object({
        title: z.string().min(1),
        paragraphs: z.array(z.string().min(1)).min(1),
      }),
    )
    .min(1),
  partnersTitle: z.string().min(1),
  partnersParagraphs: z.array(z.string().min(1)).min(1),
  closingLines: z.array(z.string().min(1)).min(1),
  contactIntro: z.string().min(1),
  contactEmail: z.string().email(),
  contactInstagramUrl: z.string().url(),
  contactInstagramHandle: z.string().min(1),
  viewerImage: z.string().min(1),
  viewerAlt: z.string().min(1),
  ctaLabel: z.string().min(1),
});

const narMailProduct = z.object({
  slug: z.literal("nar-mail-express"),
  sortOrder: z.number().int().nonnegative(),
  title: z.string().min(1),
  heroImage: z.string().min(1),
  heroAlt: z.string().min(1),
  headline: z.string().min(1),
  subheadline: z.string().min(1),
  subheadlineAside: z.string().min(1),
  statusLines: z.array(z.string().min(1)).length(3),
  aboutHeading: z.string().min(1),
  aboutParagraphs: z.array(z.string().min(1)).min(1),
  howItWorksHeading: z.string().min(1),
  dualReadingHeading: z.string().min(1),
  dualReadingIntro: z.string().min(1),
  dualReadingFirst: z.string().min(1),
  dualReadingSecond: z.string().min(1),
  dualReadingClosing: z.string().min(1),
  deliveryTimelineHeading: z.string().min(1),
  deliveryTimelineIntro: z.string().min(1),
  deliveryTimelineBullets: z.array(z.string().min(1)).min(1),
  deliveryTimelineClosing: z.string().min(1),
  serviceFeaturesHeading: z.string().min(1),
  serviceFeaturesBullets: z.array(z.string().min(1)).min(1),
  artworkCardTitle: z.string().min(1),
  artworkCardDescription: z.string().min(1),
  artworkCardButtonLabel: z.string().min(1),
  securityHeading: z.string().min(1),
  securityIntro: z.string().min(1),
  securityBlocks: z
    .array(
      z.object({
        heading: z.string().min(1),
        subheading: z.string().optional(),
        body: z.string().min(1),
      }),
    )
    .min(1),
  securityLevels: z
    .array(
      z.object({
        level: z.string().min(1),
        description: z.string().min(1),
      }),
    )
    .min(1),
  securityLevelsHeading: z.string().min(1),
  whatYouCanSendHeading: z.string().min(1),
  declaredIntro: z.string().min(1),
  declaredItems: z.array(z.string().min(1)).min(1),
  unofficialIntro: z.string().min(1),
  unofficialItems: z.array(z.string().min(1)).min(1),
  witnessHeading: z.string().min(1),
  witnessIntro: z.string().min(1),
  witnessItems: z.array(z.string().min(1)).min(1),
  witnessClosing: z.string().min(1),
  paymentHeading: z.string().min(1),
  paymentAcceptIntro: z.string().min(1),
  paymentAcceptItems: z.array(z.string().min(1)).min(1),
  paymentRefuseIntro: z.string().min(1),
  paymentRefuseItems: z.array(z.string().min(1)).min(1),
  historicalHeading: z.string().min(1),
  historicalParagraphs: z.array(z.string().min(1)).min(1),
  guaranteeHeading: z.string().min(1),
  guaranteeIntro: z.string().min(1),
  guaranteeQuoteLines: z.array(z.string().min(1)).length(2),
  guaranteeClosing: z.string().min(1),
  termsHeading: z.string().min(1),
  termsItems: z.array(z.string().min(1)).min(1),
  footerImage: z.string().min(1),
  footerImageAlt: z.string().min(1),
  footerLines: z.array(z.string().min(1)).length(9),
  footerEmail: z.string().email(),
  footerInstagramUrl: z.string().url(),
  footerInstagramHandle: z.string().min(1),
  ctaLabel: z.string().min(1),
  viewerImage: z.string().min(1),
  viewerAlt: z.string().min(1),
});

const products = defineCollection({
  type: "data",
  schema: z.discriminatedUnion("slug", [qBagProduct, narMailProduct]),
});

const contracts = defineCollection({
  type: "data",
  schema: z.object({
    slug: z.literal("afterlife-contracts"),
    sortOrder: z.number().int().nonnegative(),
    title: z.string().min(1),
    heroImage: z.string().min(1),
    heroAlt: z.string().min(1),
    heroLines: z.array(z.string().min(1)).length(2),
    heroSubheadline: z.string().min(1),
    heroSubheadlineAside: z.string().min(1),
    statusLines: z.array(z.string().min(1)).length(3),
    journeyHeading: z.string().min(1),
    journeySteps: z
      .array(
        z.object({
          number: z.string().min(1),
          label: z.string().min(1),
          detail: z.string().min(1),
          href: z.string().regex(/^#[a-z0-9-]+$/),
        }),
      )
      .length(3),
    aboutHeading: z.string().min(1),
    aboutParagraph: z.string().min(1),
    artworkCardTitle: z.string().min(1),
    artworkCardDescription: z.string().min(1),
    artworkCardButtonLabel: z.string().min(1),
    conceptHeading: z.string().min(1),
    conceptParagraphs: z.array(z.string().min(1)).length(2),
    bureaucracyHeading: z.string().min(1),
    bureaucracyParagraph: z.string().min(1),
    dualityHeading: z.string().min(1),
    dualityParagraphs: z.array(z.string().min(1)).length(2),
    visualLanguageHeading: z.string().min(1),
    visualLanguageParagraph: z.string().min(1),
    filedClausesHeading: z.string().min(1),
    filedClausesIntro: z.string().min(1),
    filedClauseSummaries: z.array(z.string().min(1)).length(4),
    interactionHeading: z.string().min(1),
    interactionIntro: z.string().min(1),
    interactionItems: z.array(z.string().min(1)).min(1),
    interactionClosing: z.string().min(1),
    closingHeading: z.string().min(1),
    closingQuoteLines: z.array(z.string().min(1)).length(2),
    downloadHeading: z.string().min(1),
    downloadIntro: z.object({
      beforeDestinations: z.string().min(1),
      destinations: z.array(z.string().min(1)).length(3),
      afterDestinations: z.string().min(1),
      clauseInstruction: z.string().min(1),
    }),
    termsHeading: z.string().min(1),
    termsIntro: z.string().min(1),
    termsItems: z.array(z.string().min(1)).min(1),
    decisionLegend: z.string().min(1),
    decisionAcceptLabel: z.string().min(1),
    decisionRefuseLabel: z.string().min(1),
    decisionAcceptedHint: z.string().min(1),
    decisionRefusedHint: z.string().min(1),
    downloadHref: z.string().min(1),
    downloadFilename: z.string().min(1),
    downloadButtonLabel: z.string().min(1),
    downloadHint: z.string().min(1),
    downloadConfirmation: z.string().min(1),
    downloadRefusedConfirmation: z.string().min(1),
    galleryClue: z.string().min(1),
    contractNote: z.string().optional(),
    contractRefusedNote: z.string().min(1),
    ctaLabel: z.string().min(1),
    viewerImage: z.string().min(1),
    viewerAlt: z.string().min(1),
  }),
});

const campaigns = defineCollection({
  type: "data",
  schema: z.object({
    slug: z.literal("president-of-the-galaxy"),
    sortOrder: z.number().int().nonnegative(),
    title: z.string().min(1),
    heroImage: z.string().min(1),
    heroAlt: z.string().min(1),
    heroTitleLines: z.array(z.string().min(1)).length(2),
    tagline: z.string().min(1),
    lead: z.string().min(1),
    statusLines: z.array(z.string().min(1)).length(3),
    artworkCardTitle: z.string().min(1),
    artworkCardDescription: z.string().min(1),
    artworkCardButtonLabel: z.string().min(1),
    whatHeading: z.string().min(1),
    whatParagraphs: z.array(z.string().min(1)).length(2),
    whatLinkHref: z.string().min(1),
    whatImage: z.string().min(1),
    dealHeading: z.string().min(1),
    dealParagraph: z.string().min(1),
    dealIncludesHeading: z.string().min(1),
    dealIncludes: z.array(z.string().min(1)).min(1),
    dealReturns: z.string().min(1),
    dealFinePrint: z.string().min(1),
    rulesHeading: z.string().min(1),
    rules: z.array(z.string().min(1)).min(1),
    promiseHeading: z.string().min(1),
    promiseLines: z.array(z.string().min(1)).length(4),
    promiseClosing: z.string().min(1),
    contactTitle: z.string().min(1),
    contactReachLine: z.string().min(1),
    contactBullets: z.array(z.string().min(1)).min(1),
    contactFor: z.string().min(1),
    contactOpenTo: z.string().min(1),
    contactEmail: z.string().email(),
    contactInstagramUrl: z.string().url(),
    contactInstagramHandle: z.string().min(1),
    contactClosing: z.string().min(1),
    ctaLabel: z.string().min(1),
    viewerImage: z.string().min(1),
    viewerAlt: z.string().min(1),
  }),
});

const knowledge = defineCollection({
  type: "content",
  schema: z.object({
    title: z.string().min(1),
    route: z.string().regex(/^\/[a-z0-9-/]*$/),
    keywords: z.array(z.string().min(1)).min(1),
    audiences: z.array(z.enum(["nar", "investor"])).min(1),
    priority: z.number().int().default(0),
  }),
});

export const collections = {
  projects,
  stickers,
  products,
  contracts,
  campaigns,
  knowledge,
};
